### ISSUE TITLE
Some questions about LOLA

### ISSUE THREAD

**Issue by SkyCloudShang** [NaoHTWK/LolaConnector#1]
Hello, I have a few questions about LOLA.
1. I have compiled the project on my computer and generated the executable file "lola_connector". Then I copy it to Nao V6 and execute the file directly. Is that all right?
2. I didn't find any detailed documentation about the use of LOLA on Softbank's official website. I only saw some simple introductions. We have only one link about LOLA:   http://doc.aldebaran.com/2-8/naoqi/lola/lola.html  . Can you provide me with some other documentation? Offline or online can be, or some examples are better. Thank you.
3. I want to know which APIs are available in lola. Previous DCM modules have onpreProcess and onPostProcess which can be used. What APIs can be used in this module now? How can I get this information?

**Comment by NaoHTWK** [comment]
Hi!
1. Yes, that's correct.
2. Documentation can be obtained by teams interested in participating in Robocup through the SPL TC or OC mailinglists.
3. This is contained in the documentation above.
